import { Injectable } from '@nestjs/common';
import Groq from 'groq-sdk';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class PresentationService {
  private groq: Groq;

  constructor() {
    this.groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
  }

  async generatePresentation(data: any): Promise<string> {
    const pptxgen = require('pptxgenjs');
    const { title, topic, audience, slides: numSlides = 8, lang = 'en-US', style = 'professional' } = data;

    const langNames: any = { 'en-US':'English', 'fr-FR':'French', 'ar-MA':'Arabic', 'es-ES':'Spanish', 'de-DE':'German' };
    const langName = langNames[lang] || 'English';

    // Generate content with AI
    const prompt = `Create a professional PowerPoint presentation in ${langName}.
Title: "${title}"
Topic: ${topic}
Target Audience: ${audience || 'Business professionals'}
Number of slides: ${numSlides}

Generate exactly ${numSlides} slides. Respond ONLY with this JSON:
{
  "slides": [
    {
      "title": "slide title",
      "content": ["bullet point 1", "bullet point 2", "bullet point 3"],
      "notes": "speaker notes"
    }
  ],
  "theme": "color suggestion"
}`;

    const response = await this.groq.chat.completions.create({
      model: 'llama-3.1-8b-instant',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 3000,
    });

    let slides = [];
    try {
      const raw = response.choices[0]?.message?.content || '{}';
      const match = raw.match(/\{[\s\S]*\}/);
      const parsed = match ? JSON.parse(match[0]) : {};
      slides = parsed.slides || [];
    } catch { slides = []; }

    // Colors
    const COLORS = {
      professional: { bg: '1A1A2E', accent: '4A3DB5', text: 'FFFFFF', sub: 'AAAACC' },
      modern: { bg: '0D1117', accent: '00D4AA', text: 'FFFFFF', sub: '888888' },
      corporate: { bg: 'FFFFFF', accent: '003087', text: '1A1A2E', sub: '666666' },
      creative: { bg: '1A0A2E', accent: 'FF6B6B', text: 'FFFFFF', sub: 'FFAAAA' },
    };
    const theme = COLORS[style as keyof typeof COLORS] || COLORS.professional;

    const pres = new pptxgen();
    pres.layout = 'LAYOUT_16x9';
    pres.author = 'ORION AI OS';
    pres.title = title;

    // Slide 1 — Cover
    const cover = pres.addSlide();
    cover.addShape(pres.ShapeType.rect, { x:0, y:0, w:10, h:5.625, fill:{ color: theme.bg } });
    cover.addShape(pres.ShapeType.rect, { x:0, y:4.2, w:10, h:1.5, fill:{ color: theme.accent } });
    cover.addText(title, { x:0.5, y:1.2, w:9, h:1.8, fontSize:40, bold:true, color:theme.text, fontFace:'Arial', align:'center' });
    cover.addText(topic || '', { x:0.5, y:3.0, w:9, h:0.7, fontSize:18, color:theme.sub, fontFace:'Arial', align:'center', italic:true });
    cover.addText('Powered by ORION AI OS', { x:0.5, y:4.5, w:9, h:0.5, fontSize:12, color:theme.text, fontFace:'Arial', align:'center' });

    // Content slides
    slides.forEach((slide: any, i: number) => {
      const s = pres.addSlide();
      s.addShape(pres.ShapeType.rect, { x:0, y:0, w:10, h:5.625, fill:{ color: theme.bg } });
      s.addShape(pres.ShapeType.rect, { x:0, y:0, w:10, h:1.2, fill:{ color: theme.accent } });
      s.addShape(pres.ShapeType.rect, { x:0, y:5.3, w:10, h:0.3, fill:{ color: theme.accent }, opacity:0.5 });

      // Slide number
      s.addText(`${i + 1} / ${slides.length}`, { x:8.5, y:5.2, w:1.2, h:0.3, fontSize:9, color:theme.sub, fontFace:'Arial', align:'right' });

      // Title
      s.addText(slide.title || '', { x:0.4, y:0.2, w:9.2, h:0.8, fontSize:22, bold:true, color:theme.text, fontFace:'Arial', valign:'middle' });

      // Content bullets
      if (slide.content?.length > 0) {
        slide.content.forEach((bullet: string, j: number) => {
          const y = 1.4 + j * 0.85;
          if (y < 4.8) {
            s.addShape(pres.ShapeType.rect, { x:0.4, y:y+0.15, w:0.12, h:0.5, fill:{ color:theme.accent } });
            s.addText(bullet, { x:0.7, y, w:8.8, h:0.8, fontSize:15, color:theme.text, fontFace:'Arial', valign:'middle' });
          }
        });
      }

      // Speaker notes
      if (slide.notes) {
        s.addNotes(slide.notes);
      }
    });

    // Last slide — Thank you
    const last = pres.addSlide();
    last.addShape(pres.ShapeType.rect, { x:0, y:0, w:10, h:5.625, fill:{ color: theme.accent } });
    last.addText('Thank You', { x:0.5, y:1.5, w:9, h:1.2, fontSize:48, bold:true, color:'FFFFFF', fontFace:'Arial', align:'center' });
    last.addText(title, { x:0.5, y:2.9, w:9, h:0.7, fontSize:18, color:'FFFFFF', fontFace:'Arial', align:'center', italic:true });
    last.addText('Generated by ORION AI OS', { x:0.5, y:4.8, w:9, h:0.4, fontSize:11, color:'FFFFFF', fontFace:'Arial', align:'center' });

    // Save
    const outputDir = '/tmp/orion_presentations';
    fs.mkdirSync(outputDir, { recursive: true });
    const filename = `presentation_${Date.now()}.pptx`;
    const filepath = path.join(outputDir, filename);
    await pres.writeFile({ fileName: filepath });

    return filepath;
  }
}
